imports:
    - { resource: config_dev.yml }

# this cache is used during tests when setting up pimcore
pimcore:
    cache:
        pool_service_id: pimcore.cache.core.pool.array

doctrine:
    dbal:
        connections:
            default:
                host: mysql
                port: 3306
                dbname: database2
                user: user
                password: password
                charset: utf8mb4
                server_version: '5.7'
