services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #
    # Controllers
    #

    Divante\DocumentCopierBundle\Controller\:
        resource: '../../Controller'
        public: true
        autowire: true
        tags: ['controller.service_arguments']

    Divante\DocumentCopierBundle\Controller\AdminController: ~

    #
    # Commands
    #

    Divante\DocumentCopierBundle\Command\:
        resource: '../../Command'
        tags: ['console.command']

    Divante\DocumentCopierBundle\Command\DocumentExportCommand:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'

    Divante\DocumentCopierBundle\Command\DocumentImportCommand:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'

    #
    # Services
    #

    Divante\DocumentCopierBundle\Service\:
        resource: '../../Service'

    Divante\DocumentCopierBundle\Service\FileService:
        arguments:
            $kernelProjectDir: '%kernel.project_dir%'