name: Tests
on: [push]

jobs:
    build:
        name: Tests
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: database2
                ports:
                    - 33306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Setup DB
              run: |
                  mysql --version
                  mysql -u root -proot -e "SET GLOBAL innodb_file_format=Barracuda;"
                  mysql -u root -proot -e "SET GLOBAL innodb_large_prefix=1;"

            - name: PHP Runner
              uses: nanasess/setup-php@master
              with:
                  php-version: '7.3'

            - name: Checkout Repository
              uses: actions/checkout@v1

            - name: Install project and run tests
              env:
                  DB_HOST: "mysql"
                  DB_PORT: "3306"
                  DB_USERNAME: "root"
                  DB_PASSWORD: "root"
                  DB_DATABASE: "database2"
                  PIMCORE_ENVIRONMENT: "test"
                  PIMCORE_TEST: "1"
                  PIMCORE_TEST_DB_DSN: "mysql://root:root@localhost/database2"
              run: |
                  bash ./scripts/codeception.sh
